int:
  web_request_host: http://int-laxpower-phpadmin-01w.dev.activenetwork.com
  api_request_host: https://awmobile-vip.qa.aw.dev.activenetwork.com

prod:
  web_request_host: http://php.admin.laxpower.com
  api_request_host: https://awmobile.active.com

